# Markdown config
markdown: redcarpet
highlighter: rouge
name: U.S. Web Design Standards
exclude:
- go
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- CONTRIBUTING.md
- ".sass-cache"
- ".ruby-version"
- vendor

permalink: pretty

repos:
- name: U.S. Web Design Standards
  description: Main repository for the U.S. Web Design Standards.
  url: https://github.com/18F/web-design-standards
- name: U.S. Federal Web Design Standards Assets
  description: U.S. Federal Web Design Standards visual design assets
  url: https://github.com/18F/web-design-standards-assets

google_analytics_ua: UA-48605964-33

sass:
  sass_dir: assets/_scss
#  style: :compressed

collections:
  visual:
    output: true
    permalink: /:path/
  layout-system:
    output: true
    permalink: /:path/
  elements:
    output: true
    permalink: /:path/
  components:
    output: true
    permalink: /:path/
